### ISSUE TITLE
seeking advice

### ISSUE THREAD

**Issue by rudolph-the-red-nose-reindeer** [muschellij2/spm12r#5]
I am looking to use the output from your preprocessing pipeline, ie. the swa file that can be found in the output directory to construct a first level model and investigate the resting state connectivity between 2 regions of the brain. I was wondering if you have any advice on the automation of this process, or how you would go about this? The tutorial I was following had multiple images as the input to the model, but the output of the preprocessing pipeline seems to have only one smoothed image. I am a little confused about that.

**Comment by muschellij2** [comment]
I don't understand your question.  One part of my confusion is "first level model and investigate the resting state connectivity".  First level models are typically used in task-related fMRI analysis, where the model is the fMRI data regressed on the hemodynamic response function (HRF) and the task vector of responses.  So that's not really done in resting state connectivity analyses.  So the swa* file is **a**ligned, then **w**arped, and **s**moothed.  That preprocessing is mapped out in the vignettes.   This should be a 4D file.  Then, if you have the regions of interest (ROI) (in a 3D mask or atlas/segmentation in template space), then you can take the voxels in a region, average them to get an average time course, do the same for another ROI, and then calculate the correlation.  If you do that for a number of regions, you will have a connectivity matrix.  There is disputes whether this should be inverted to give a partial correlation matrix.
